# Generated by Django 3.0.5 on 2023-02-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la rutina')),
                ('count', models.IntegerField(default=0, verbose_name='Contador numérico')),
                ('percent', models.FloatField(default=0.0, verbose_name='Contador de porcentaje')),
                ('color', models.CharField(choices=[('Red', 'Rojo'), ('Green', 'Verde'), ('Blue', 'Azul'), ('Yellow', 'Amarillo'), ('Black', 'Negro'), ('White', 'Blanco')], default='Red', max_length=20, verbose_name='Color')),
                ('image', models.ImageField(blank=True, default='null', upload_to='', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
                'ordering': ['-created_at'],
            },
        ),
    ]
