# Generated by Django 3.0.5 on 2023-02-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_tareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorNumerico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Contador numérico')),
            ],
        ),
    ]
