# Generated by Django 3.0.5 on 2023-02-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_contadornumerico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('contador', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='contadornumerico',
            old_name='count',
            new_name='contador',
        ),
    ]
