# Generated by Django 3.0.5 on 2023-04-13 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0004_auto_20230224_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contador',
        ),
        migrations.DeleteModel(
            name='ContadorNumerico',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.AddField(
            model_name='tareas',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='¿Completada?'),
        ),
        migrations.AddField(
            model_name='tareas',
            name='user',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
